# Generated by Django 6.0.6 on 2026-07-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario', models.CharField(blank=True, max_length=200)),
                ('domicilio', models.CharField(blank=True, max_length=300)),
                ('nivel_riesgo', models.CharField(blank=True, max_length=30)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('comisaria', models.CharField(blank=True, max_length=200)),
                ('efectivo', models.CharField(blank=True, max_length=100)),
                ('folder', models.CharField(blank=True, max_length=100)),
                ('expediente', models.CharField(blank=True, max_length=100)),
                ('agresor', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('ultima_visita', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('notificacion', models.CharField(blank=True, max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
