# Generated by Django 6.0.6 on 2026-07-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='distrito',
            field=models.CharField(blank=True, choices=[('EL AGUSTINO', 'EL AGUSTINO'), ('ATE', 'ATE'), ('SANTA ANITA', 'SANTA ANITA'), ('SAN LUIS', 'SAN LUIS'), ('LA VICTORIA', 'LA VICTORIA'), ('RIMAC', 'RIMAC'), ('CERCADO DE LIMA', 'CERCADO DE LIMA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='caso',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nivel_riesgo',
            field=models.CharField(blank=True, choices=[('LEVE', 'LEVE'), ('MODERADO', 'MODERADO'), ('SEVERO1', 'SEVERO1'), ('SEVERO2', 'SEVERO2'), ('NO DETERMINADO', 'NO DETERMINADO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='caso',
            name='notificacion',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
    ]
