# Generated by Django 6.0.6 on 2026-07-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_alter_caso_distrito_alter_caso_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=15),
        ),
        migrations.AlterField(
            model_name='caso',
            name='notificacion',
            field=models.CharField(max_length=100),
        ),
    ]
