# Generated by Django 6.0.6 on 2026-07-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_caso_estado_alter_caso_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='notificacion',
        ),
        migrations.AddField(
            model_name='caso',
            name='dni_agresor',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='caso',
            name='dni_beneficiario',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='caso',
            name='fecha_notificacion_agresor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='fecha_notificacion_beneficiario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='notificacion_agresor',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADO', 'Notificado')], default='NO', max_length=15),
        ),
        migrations.AddField(
            model_name='caso',
            name='notificacion_beneficiario',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADO', 'Notificado')], default='NO', max_length=15),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nivel_riesgo',
            field=models.CharField(blank=True, choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('SEVERO', 'Severo'), ('SEVERO EXTREMO', 'Severo extremo'), ('NO DETERMINADO', 'No determinado')], max_length=30),
        ),
    ]
