# Generated by Django 6.0.6 on 2026-07-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_remove_caso_notificacion_caso_dni_agresor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='notificacion_agresor',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADO', 'Notificado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='caso',
            name='notificacion_beneficiario',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADO', 'Notificado')], default='PENDIENTE', max_length=15),
        ),
    ]
