# Generated by Django 6.0.6 on 2026-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_solicitudmodificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo seguimiento'),
        ),
    ]
