# Generated by Django 6.0.6 on 2026-07-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0007_alter_caso_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='edicion_autorizada',
            field=models.BooleanField(default=False),
        ),
    ]
