# Generated by Django 6.0.6 on 2026-07-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0008_caso_edicion_autorizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caso',
            options={'permissions': [('modificar_directo', 'Puede modificar casos directamente'), ('aprobar_modificacion', 'Puede aprobar modificaciones'), ('archivar_directo', 'Puede archivar casos directamente'), ('aprobar_archivado', 'Puede aprobar archivados'), ('eliminar_directo', 'Puede eliminar casos directamente'), ('aprobar_eliminacion', 'Puede aprobar eliminaciones'), ('administrar_usuarios', 'Puede administrar usuarios')]},
        ),
    ]
