# Generated by Django 6.0.6 on 2026-07-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0011_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='caso',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mapa.caso'),
            preserve_default=False,
        ),
    ]
