# Generated by Django 6.0.6 on 2026-07-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0012_mensaje_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
