# Generated by Django 6.0.6 on 2026-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0013_mensaje_fecha_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='direccion_agresor',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección del agresor'),
        ),
        migrations.AddField(
            model_name='caso',
            name='telefono_agresor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono del agresor'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono de la beneficiaria'),
        ),
    ]
