# Generated by Django 6.0.6 on 2026-07-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0014_caso_direccion_agresor_caso_telefono_agresor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='motivo_notificacion_agresor_pendiente',
            field=models.TextField(blank=True, verbose_name='Motivo de notificación pendiente de la persona agresora'),
        ),
        migrations.AddField(
            model_name='caso',
            name='motivo_notificacion_beneficiario_pendiente',
            field=models.TextField(blank=True, verbose_name='Motivo de notificación pendiente de la persona beneficiaria'),
        ),
    ]
