# Generated by Django 6.0.6 on 2026-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0015_caso_motivo_notificacion_agresor_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='fecha_denuncia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la denuncia'),
        ),
    ]
