# Generated by Django 6.0.6 on 2026-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0016_caso_fecha_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='violencia_economica',
            field=models.BooleanField(default=False, verbose_name='Violencia económica o patrimonial'),
        ),
        migrations.AddField(
            model_name='caso',
            name='violencia_fisica',
            field=models.BooleanField(default=False, verbose_name='Violencia física'),
        ),
        migrations.AddField(
            model_name='caso',
            name='violencia_psicologica',
            field=models.BooleanField(default=False, verbose_name='Violencia psicológica'),
        ),
        migrations.AddField(
            model_name='caso',
            name='violencia_sexual',
            field=models.BooleanField(default=False, verbose_name='Violencia sexual'),
        ),
    ]
