# Generated by Django 6.0.6 on 2026-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0017_caso_violencia_economica_caso_violencia_fisica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='comisaria',
        ),
        migrations.AddField(
            model_name='caso',
            name='comisaria_denuncia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Comisaría donde se interpuso la denuncia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='comisaria_medida',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Comisaría de Familia responsable'),
        ),
    ]
