# Generated by Django 6.0.6 on 2026-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0018_remove_caso_comisaria_caso_comisaria_denuncia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='comisaria_denuncia',
            field=models.CharField(default='NO REGISTRADA', max_length=100, verbose_name='Comisaría donde se interpuso la denuncia'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='comisaria_medida',
            field=models.CharField(default='NO REGISTRADA', max_length=100, verbose_name='Comisaría de Familia responsable'),
        ),
    ]
