# Generated by Django 6.0.6 on 2026-07-30 16:32

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0019_alter_caso_comisaria_denuncia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=100,
                        unique=True
                    )
                ),
            ],
        ),

        migrations.CreateModel(
            name='Provincia',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=100
                    )
                ),
                (
                    'region',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='provincias',
                        to='mapa.region'
                    )
                ),
            ],
        ),

        migrations.CreateModel(
            name='Distrito',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=100
                    )
                ),
                (
                    'provincia',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='distritos',
                        to='mapa.provincia'
                    )
                ),
            ],
        ),
    ]
