# Generated by Django 6.0.6 on 2026-07-30 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0020_auto_20260730_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='distrito',
        ),
        migrations.AddField(
            model_name='caso',
            name='distrito_denuncia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_denuncia_distrito', to='mapa.distrito'),
        ),
        migrations.AddField(
            model_name='caso',
            name='distrito_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_medida_distrito', to='mapa.distrito'),
        ),
        migrations.AddField(
            model_name='caso',
            name='provincia_denuncia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_denuncia_provincia', to='mapa.provincia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='provincia_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_medida_provincia', to='mapa.provincia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='region_denuncia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_denuncia_region', to='mapa.region'),
        ),
        migrations.AddField(
            model_name='caso',
            name='region_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos_medida_region', to='mapa.region'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='comisaria_denuncia',
            field=models.CharField(max_length=150, verbose_name='Comisaría donde se interpuso la denuncia'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='comisaria_medida',
            field=models.CharField(max_length=150, verbose_name='Comisaría de Familia responsable'),
        ),
    ]
