# Generated by Django 6.0.6 on 2026-07-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0021_remove_caso_distrito_caso_distrito_denuncia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
