# Generated by Django 6.0.6 on 2026-07-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0022_distrito_codigo_provincia_codigo_region_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='region',
            name='codigo',
        ),
        migrations.AddField(
            model_name='distrito',
            name='codigo_ubigeo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='distrito',
            name='id_ubigeo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='codigo_ubigeo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_ubigeo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='codigo_ubigeo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='region',
            name='id_ubigeo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
