# Generated by Django 6.0.6 on 2026-07-30 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0023_remove_distrito_codigo_remove_provincia_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionPreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaria', models.CharField(max_length=150)),
                ('dni_beneficiaria', models.CharField(max_length=8)),
                ('domicilio', models.TextField()),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_preliminares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
