# Generated by Django 6.0.6 on 2026-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0024_ubicacionpreliminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='estado_ubicacion_agresor',
            field=models.CharField(choices=[('UBICADO', 'Ubicado'), ('NO UBICADO', 'No ubicado')], default='NO UBICADO', max_length=15, verbose_name='Estado de ubicación del agresor'),
        ),
        migrations.AddField(
            model_name='caso',
            name='latitud_agresor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='longitud_agresor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
