# Generated by Django 6.0.6 on 2026-07-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0025_caso_estado_ubicacion_agresor_caso_latitud_agresor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='agresor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de la persona agresora'),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='direccion_agresor',
            field=models.TextField(blank=True, verbose_name='Domicilio de la persona agresora'),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='dni_agresor',
            field=models.CharField(blank=True, max_length=8, verbose_name='DNI de la persona agresora'),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='estado_ubicacion_agresor',
            field=models.CharField(choices=[('UBICADO', 'Ubicado'), ('NO UBICADO', 'No ubicado')], default='NO UBICADO', max_length=15, verbose_name='¿La víctima conoce el domicilio del agresor?'),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='latitud_agresor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='longitud_agresor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
