# Generated by Django 6.0.6 on 2026-07-31 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0026_ubicacionpreliminar_agresor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='estado',
            field=models.CharField(choices=[('PRELIMINAR', 'Preliminar'), ('CONVERTIDA', 'Convertida en medida'), ('VENCIDA', 'Vencida')], default='PRELIMINAR', max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('CONOCIDO', 'Agresor con domicilio conocido'), ('DESCONOCIDO', 'Agresor sin domicilio conocido')], default='CONOCIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='agresor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='beneficiaria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='direccion_agresor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='dni_agresor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='dni_beneficiaria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='estado_ubicacion_agresor',
            field=models.CharField(choices=[('CONOCIDO', 'Agresor con domicilio conocido'), ('DESCONOCIDO', 'Agresor sin domicilio conocido')], default='CONOCIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
