# Generated by Django 6.0.6 on 2026-08-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0028_agresor_caso_agresor_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacionpreliminar',
            old_name='agresor',
            new_name='denunciado',
        ),
        migrations.RenameField(
            model_name='ubicacionpreliminar',
            old_name='beneficiaria',
            new_name='denunciante',
        ),
        migrations.RenameField(
            model_name='ubicacionpreliminar',
            old_name='direccion_agresor',
            new_name='direccion_denunciado',
        ),
        migrations.RenameField(
            model_name='ubicacionpreliminar',
            old_name='domicilio',
            new_name='direccion_denunciante',
        ),
        migrations.RenameField(
            model_name='ubicacionpreliminar',
            old_name='dni_agresor',
            new_name='dni_denunciado',
        ),
        migrations.RenameField(
            model_name='ubicacionpreliminar',
            old_name='dni_beneficiaria',
            new_name='dni_denunciante',
        ),
        migrations.RenameField(
            model_name='ubicacionpreliminar',
            old_name='latitud_agresor',
            new_name='latitud_denunciado',
        ),
        migrations.RenameField(
            model_name='ubicacionpreliminar',
            old_name='longitud_agresor',
            new_name='latitud_denunciante',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='estado_ubicacion_agresor',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='referencia',
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='longitud_denunciado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='longitud_denunciante',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='participante_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='participante_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='telefono_denunciante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='tipo_intervencion',
            field=models.CharField(blank=True, choices=[('UNILATERAL', 'Agresión unilateral'), ('MUTUA', 'Agresión mutua')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='tipo_registro',
            field=models.CharField(choices=[('DENUNCIA', 'Denuncia'), ('INTERVENCION', 'Intervención policial')], default='DENUNCIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacionpreliminar',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('CONOCIDO', 'Ubicación conocida'), ('DESCONOCIDO', 'Ubicación desconocida')], default='DESCONOCIDO', max_length=20),
        ),
    ]
