# Generated by Django 6.0.6 on 2026-08-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0029_rename_agresor_ubicacionpreliminar_denunciado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaPreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('dni', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('requiere_ubicacion', models.BooleanField(default=False)),
                ('ubicacion_preliminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='mapa.ubicacionpreliminar')),
            ],
        ),
        migrations.CreateModel(
            name='RolPersonaPreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('DENUNCIANTE', 'Denunciante'), ('PRESUNTA_VICTIMA', 'Presunta víctima'), ('DENUNCIADO', 'Denunciado'), ('PARTICIPANTE', 'Participante')], max_length=30)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='mapa.personapreliminar')),
            ],
        ),
    ]
