# Generated by Django 6.0.6 on 2026-08-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0030_personapreliminar_rolpersonapreliminar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='denunciado',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='denunciante',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='direccion_denunciado',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='direccion_denunciante',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='dni_denunciado',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='dni_denunciante',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='latitud_denunciado',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='latitud_denunciante',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='longitud_denunciado',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='longitud_denunciante',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='participante_1',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='participante_2',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='telefono_denunciante',
        ),
        migrations.RemoveField(
            model_name='ubicacionpreliminar',
            name='tipo_ubicacion',
        ),
    ]
