# Generated by Django 6.0.6 on 2026-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0031_remove_ubicacionpreliminar_denunciado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personapreliminar',
            name='rol_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
