# Generated by Django 6.0.6 on 2026-08-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0032_personapreliminar_rol_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='personapreliminar',
            name='convertida',
            field=models.BooleanField(default=False),
        ),
    ]
