# Generated by Django 6.0.6 on 2026-08-03 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0033_personapreliminar_convertida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personapreliminar',
            name='condicion_actual',
            field=models.CharField(blank=True, choices=[('BENEFICIARIO', 'Beneficiario/a'), ('AGRESOR', 'Agresor/a'), ('AMBOS', 'Beneficiario/a y Agresor/a')], max_length=20, null=True, verbose_name='Condición actual'),
        ),
        migrations.AddField(
            model_name='personapreliminar',
            name='fecha_actualizacion_condicion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización de la condición'),
        ),
        migrations.AddField(
            model_name='personapreliminar',
            name='motivo_actualizacion_condicion',
            field=models.TextField(blank=True, verbose_name='Motivo o disposición que sustenta la condición'),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='alcance_medida',
            field=models.CharField(blank=True, choices=[('UNA_PERSONA', 'Medida de protección a favor de una persona'), ('AMBAS_PERSONAS', 'Medida de protección a favor de ambas personas')], max_length=20, null=True, verbose_name='Alcance de la medida de protección'),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='caso_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_preliminares_origen', to='mapa.caso', verbose_name='Caso generado'),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='convertida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_preliminares_convertidas', to=settings.AUTH_USER_MODEL, verbose_name='Convertida por'),
        ),
        migrations.AddField(
            model_name='ubicacionpreliminar',
            name='fecha_conversion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conversión'),
        ),
    ]
