# Generated by Django 6.0.6 on 2026-08-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0035_caso_eliminado_por_caso_fecha_eliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='notificacion_vencimiento_leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudmodificacion',
            name='notificacion_leida',
            field=models.BooleanField(default=False),
        ),
    ]
