# Generated by Django 6.0.6 on 2026-08-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0037_caso_complemento_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agresor',
            name='distrito_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agresores_distrito_domicilio', to='mapa.distrito'),
        ),
        migrations.AddField(
            model_name='agresor',
            name='provincia_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agresores_provincia_domicilio', to='mapa.provincia'),
        ),
        migrations.AddField(
            model_name='agresor',
            name='region_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agresores_region_domicilio', to='mapa.region'),
        ),
        migrations.AddField(
            model_name='caso',
            name='distrito_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_distrito_domicilio', to='mapa.distrito'),
        ),
        migrations.AddField(
            model_name='caso',
            name='provincia_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_provincia_domicilio', to='mapa.provincia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='region_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_region_domicilio', to='mapa.region'),
        ),
    ]
