# Generated by Django 6.0.6 on 2026-08-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0038_agresor_distrito_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='distrito_agresor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_distrito_agresor', to='mapa.distrito'),
        ),
        migrations.AddField(
            model_name='caso',
            name='provincia_agresor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_provincia_agresor', to='mapa.provincia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='region_agresor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_region_agresor', to='mapa.region'),
        ),
    ]
