# Generated by Django 6.0.6 on 2026-08-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0039_caso_distrito_agresor_caso_provincia_agresor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='complemento_domicilio_agresor',
            field=models.CharField(blank=True, max_length=300, verbose_name='Complemento / referencia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='nombre_via_agresor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de vía'),
        ),
        migrations.AddField(
            model_name='caso',
            name='numero_via_agresor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='caso',
            name='tipo_via_agresor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tipo de vía'),
        ),
    ]
