# Generated by Django 6.0.6 on 2026-09-07 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0040_caso_complemento_domicilio_agresor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_activacion', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ACEPTADA', 'Aceptada'), ('EN_CAMINO', 'En camino'), ('EN_LUGAR', 'En el lugar'), ('FINALIZADA', 'Finalizada'), ('FALSA', 'Falsa alarma')], default='ACTIVA', max_length=20)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_en_camino', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_emergencia', to='mapa.caso')),
            ],
            options={
                'verbose_name': 'Alerta de emergencia',
                'verbose_name_plural': 'Alertas de emergencia',
                'ordering': ['-fecha_hora_activacion'],
            },
        ),
    ]
