# Generated by Django 6.0.6 on 2026-09-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0041_alertaemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=30)),
                ('mensaje_inicial', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ESPERANDO_UBICACION', 'Esperando ubicación'), ('UBICACION_RECIBIDA', 'Ubicación recibida'), ('ALERTA_CREADA', 'Alerta creada'), ('NO_IDENTIFICADA', 'Número no identificado')], default='ESPERANDO_UBICACION', max_length=30)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('mensaje_whatsapp_id', models.CharField(blank=True, max_length=200)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_whatsapp', to='mapa.alertaemergencia')),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_whatsapp', to='mapa.caso')),
            ],
            options={
                'verbose_name': 'Solicitud de auxilio por WhatsApp',
                'verbose_name_plural': 'Solicitudes de auxilio por WhatsApp',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
